# Generated by Django 3.1.5 on 2021-01-08 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsApp', '0002_auto_20210108_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 10, 47, 35, 303565, tzinfo=utc)),
        ),
    ]
