# Generated by Django 3.1.5 on 2021-01-08 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_auto_20210108_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 10, 50, 45, 842756, tzinfo=utc)),
        ),
    ]
