# Generated by Django 3.1.5 on 2021-01-08 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20210108_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sportnews',
            name='description',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 8, 11, 51, 3, 399787, tzinfo=utc)),
        ),
    ]
